name: Official Junie GitHub Action (BETA)
run-name: Junie run ${{ inputs.run_id }}

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: "id of workflow process"
        required: true
      workflow_params:
        description: "stringified params"
        required: true

jobs:
  call-workflow-passing-data:
    uses: JetBrains/junie-github-action@v0.3.0
    with:
      workflow_params: ${{ inputs.workflow_params }}
